swagger: "2.0"
info:
  version: "1.0.0"
  title: "Sunglasses"
  description: "API for e-commerce sunglasses store managing brands, products, and user cart"
host: "localhost:3000"
schemes:
  - "http"
basePath: "/api"
produces:
  - "application/json"
paths:
  /products:
    tags:
      - "products"
    summary: "returns all products"
    description: ""
    produces:
      - "application/json"
